version: '{build}-{branch}'
image: Visual Studio 2017

skip_commits:
  files:
    - '**/*.md'
    
build_script:
- pwsh: dotnet build -c Release

test_script:
- pwsh: dotnet test test -c Release --no-build

after_test:
- pwsh:  dotnet pack $env:APPVEYOR_BUILD_FOLDER\src -c Release --include-symbols --no-build -o artifacts\nuget

artifacts:
- path: '**\artifacts\nuget\*.nupkg'
  name: Nuget
  
deploy:
- provider: NuGet
  api_key:
    secure: N5hPFSyZf1EHN9bQ2Bj+0qfuAcxSVpanQqos6kJyUY/IK280ET4IZziCGU/nKiAn
  artifact: NuGet
  on:
    appveyor_repo_tag: true   
